"""Tests for Slack response formatters."""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from uuid import uuid4

from dacribagents.application.ports.calendar_adapter import CalendarEvent, DateRange
from dacribagents.application.use_cases.reminder_queries import (
    DraftPreview,
    ReminderExplanation,
    ScheduleSummary,
)
from dacribagents.domain.reminders.entities import Reminder, ReminderTarget
from dacribagents.domain.reminders.enums import (
    CalendarProviderType,
    DeliveryChannel,
    NotificationIntent,
    ReminderSource,
    ReminderState,
    TargetType,
    UrgencyLevel,
)
from dacribagents.infrastructure.slack.formatters import (
    format_approval_list,
    format_calendar_conflicts,
    format_draft_preview,
    format_explanation,
    format_reminder_list,
    format_schedule_summary,
)


def _make_reminder(**kwargs) -> Reminder:
    defaults = {
        "id": uuid4(),
        "household_id": uuid4(),
        "subject": "Test reminder",
        "body": "Test body",
        "urgency": UrgencyLevel.NORMAL,
        "source": ReminderSource.USER,
        "state": ReminderState.DRAFT,
        "created_by": uuid4(),
        "created_at": datetime(2026, 3, 28),
        "updated_at": datetime(2026, 3, 28),
    }
    defaults.update(kwargs)
    return Reminder(**defaults)


# ── Reminder list ───────────────────────────────────────────────────────────


def test_format_empty_list():
    result = format_reminder_list([], "Test")
    assert "No items" in result


def test_format_reminder_list():
    reminders = [
        _make_reminder(subject="Trash day", urgency=UrgencyLevel.NORMAL),
        _make_reminder(subject="Inverter alarm", urgency=UrgencyLevel.URGENT, intent=NotificationIntent.ALERT),
    ]
    result = format_reminder_list(reminders, "Active")
    assert "2 items" in result
    assert "Trash day" in result
    assert "Inverter alarm" in result


# ── Approval list ───────────────────────────────────────────────────────────


def test_format_approval_list_empty():
    result = format_approval_list([])
    assert "clear" in result.lower()


def test_format_approval_list():
    reminders = [_make_reminder(subject="HOA deadline", source=ReminderSource.HOA)]
    result = format_approval_list(reminders)
    assert "HOA deadline" in result
    assert "approval" in result.lower()


# ── Explanation ─────────────────────────────────────────────────────────────


def test_format_explanation():
    r = _make_reminder(
        subject="Warranty expiring",
        source=ReminderSource.WARRANTY,
        requires_approval=True,
    )
    expl = ReminderExplanation(
        reminder=r,
        targets=[
            ReminderTarget(id=uuid4(), reminder_id=r.id, target_type=TargetType.HOUSEHOLD),
        ],
        schedule=None,
        approval_reason="Reminders from 'warranty' sources require approval",
        source_description="Generated by the warranty tracker",
        lifecycle_summary="Current state: draft. Active.",
    )
    result = format_explanation(expl)
    assert "Warranty expiring" in result
    assert "warranty" in result.lower()
    assert "approval" in result.lower()


# ── Draft preview ───────────────────────────────────────────────────────────


def test_format_draft_preview():
    preview = DraftPreview(
        subject="Soccer practice",
        body="Don't forget cleats",
        intent=NotificationIntent.REMINDER,
        urgency=UrgencyLevel.NORMAL,
        source=ReminderSource.USER,
        target_description="Targets the entire household",
        schedule_description="One-shot at 5pm",
        likely_channels=[DeliveryChannel.SLACK, DeliveryChannel.EMAIL],
        requires_approval=False,
        approval_reason=None,
        notes=[],
    )
    result = format_draft_preview(preview)
    assert "Soccer practice" in result
    assert "household" in result.lower()
    assert "No approval required" in result


def test_format_draft_preview_with_approval():
    preview = DraftPreview(
        subject="Maintenance check",
        body="",
        intent=NotificationIntent.ALERT,
        urgency=UrgencyLevel.URGENT,
        source=ReminderSource.MAINTENANCE,
        target_description="Targets the entire household",
        schedule_description=None,
        likely_channels=[DeliveryChannel.SMS, DeliveryChannel.SLACK],
        requires_approval=True,
        approval_reason="Agent-sourced",
        notes=["No body text — consider adding details for the recipient."],
    )
    result = format_draft_preview(preview)
    assert "Approval required" in result
    assert "Notes" in result


# ── Schedule summary ────────────────────────────────────────────────────────


def test_format_schedule_summary():
    tz = timezone(timedelta(hours=-5))
    tomorrow = datetime.now(tz=tz).replace(hour=0, minute=0, second=0) + timedelta(days=1)
    summary = ScheduleSummary(
        reminders=[_make_reminder(subject="Trash day")],
        calendar_events=[
            CalendarEvent(
                id="e1",
                title="Soccer",
                start=tomorrow.replace(hour=17),
                end=tomorrow.replace(hour=18, minute=30),
                source=CalendarProviderType.MANUAL,
                owner_identity_id=uuid4(),
            )
        ],
        date_range=DateRange(start=tomorrow, end=tomorrow + timedelta(days=1)),
    )
    result = format_schedule_summary(summary)
    assert "Soccer" in result
    assert "Trash day" in result


# ── Calendar conflicts ──────────────────────────────────────────────────────


def test_format_calendar_conflicts_none():
    result = format_calendar_conflicts([], "Thursday")
    assert "clear" in result.lower()


def test_format_calendar_conflicts():
    tz = timezone(timedelta(hours=-5))
    now = datetime.now(tz=tz)
    events = [
        CalendarEvent(
            id="e2",
            title="Band rehearsal",
            start=now.replace(hour=19),
            end=now.replace(hour=21),
            source=CalendarProviderType.MANUAL,
            owner_identity_id=uuid4(),
        )
    ]
    result = format_calendar_conflicts(events, "Thursday night")
    assert "Band rehearsal" in result
