"""Household reminder orchestration domain."""

from dacribagents.domain.reminders.entities import (
    ApprovalRecord,
    CalendarAccessPolicy,
    CalendarIdentity,
    CalendarProvider,
    Household,
    HouseholdMember,
    MemberDevice,
    PreferenceRule,
    Reminder,
    ReminderAcknowledgement,
    ReminderContextSource,
    ReminderDelivery,
    ReminderExecution,
    ReminderSchedule,
    ReminderTarget,
)
from dacribagents.domain.reminders.enums import (
    AckMethod,
    ApprovalAction,
    CalendarAccessLevel,
    CalendarProviderType,
    DeliveryChannel,
    DeliveryStatus,
    DevicePlatform,
    MemberRole,
    NotificationIntent,
    ReminderSource,
    ReminderState,
    ScheduleType,
    TargetType,
    UrgencyLevel,
)
from dacribagents.domain.reminders.lifecycle import (
    TERMINAL_STATES,
    VALID_TRANSITIONS,
    InvalidTransitionError,
    can_transition,
    is_terminal,
    reachable_states,
    validate_transition,
)

__all__ = [
    # Enums
    "AckMethod",
    "ApprovalAction",
    "CalendarAccessLevel",
    "CalendarProviderType",
    "DeliveryChannel",
    "DeliveryStatus",
    "DevicePlatform",
    "MemberRole",
    "NotificationIntent",
    "ReminderSource",
    "ReminderState",
    "ScheduleType",
    "TargetType",
    "UrgencyLevel",
    # Entities
    "ApprovalRecord",
    "CalendarAccessPolicy",
    "CalendarIdentity",
    "CalendarProvider",
    "Household",
    "HouseholdMember",
    "MemberDevice",
    "PreferenceRule",
    "Reminder",
    "ReminderAcknowledgement",
    "ReminderContextSource",
    "ReminderDelivery",
    "ReminderExecution",
    "ReminderSchedule",
    "ReminderTarget",
    # Lifecycle
    "InvalidTransitionError",
    "TERMINAL_STATES",
    "VALID_TRANSITIONS",
    "can_transition",
    "is_terminal",
    "reachable_states",
    "validate_transition",
]
